### ISSUE TITLE
Apriori - Subset name error

### ISSUE THREAD

**Issue by zpencerguy** [eriklindernoren/ML-From-Scratch#12]
Name subset missing s (subsets) at line 158?

NameError                                 Traceback (most recent call last)
<ipython-input-117-5dfcb657789c> in <module>()
     17 
     18 # Get and print the rules
---> 19 rules = apriori.generate_rules(transactions)
     20 print ("Rules:")
     21 for rule in rules:

<ipython-input-116-c89fd55eb61b> in generate_rules(self, transactions)
    167         rules = []
    168         for itemset in frequent_itemsets:
--> 169             rules += self._rules_from_itemset(itemset, itemset)
    170         return rules

<ipython-input-116-c89fd55eb61b> in _rules_from_itemset(self, initial_itemset, itemset)
    156                 # recursively add rules from subsets
    157                 if k - 1 > 1:
--> 158                     rules.append(self._rules_from_itemset(initial_itemset, subset))
    159         return rules
    160 

NameError: name 'subset' is not defined

**Comment by eriklindernoren** [comment]
Thanks. This should be fixed in the latest commit.

**Comment by eriklindernoren** [comment]
- Apriori -
Minimum - support: 0.25, confidence: 0.8
Transactions:
	[1, 2, 3, 4]
	[1, 2, 4]
	[1, 2]
	[2, 3, 4]
	[2, 3]
	[3, 4]
	[2, 4]
Frequent Itemsets:
	[1, 2, 3, 4, [1, 2], [1, 4], [2, 3], [2, 4], [3, 4], [1, 2, 4], [2, 3, 4]]
Rules:
	1 -> 2 (support: 0.43, confidence: 1.0)
	4 -> 2 (support: 0.57, confidence: 0.8)
	[1, 4] -> 2 (support: 0.29, confidence: 1.0)
