### ISSUE TITLE
Apriori - Zero Division Error

### ISSUE THREAD

**Issue by zpencerguy** [eriklindernoren/ML-From-Scratch#13]
After adding s to subsets (previous issue) I'm getting the list of frequent itemsets but no rules. Intentionally set my support very low to see if I could get a 2-itemset antecedent, roughly 2%. Not an issue with greater support.

ZeroDivisionError                         Traceback (most recent call last)
<ipython-input-119-5dfcb657789c> in <module>()
     17 
     18 # Get and print the rules
---> 19 rules = apriori.generate_rules(transactions)
     20 print ("Rules:")
     21 for rule in rules:

<ipython-input-118-7741dd66b679> in generate_rules(self, transactions)
    167         rules = []
    168         for itemset in frequent_itemsets:
--> 169             rules += self._rules_from_itemset(itemset, itemset)
    170         return rules

<ipython-input-118-7741dd66b679> in _rules_from_itemset(self, initial_itemset, itemset)
    156                 # recursively add rules from subsets
    157                 if k - 1 > 1:
--> 158                     rules.append(self._rules_from_itemset(initial_itemset, subsets))
    159         return rules
    160 

<ipython-input-118-7741dd66b679> in _rules_from_itemset(self, initial_itemset, itemset)
    136             # Calculate the confidence as sup(A and B) / sup(B), if antecedent
    137             # is B in an itemset of A and B
--> 138             confidence = float("{0:.2f}".format(support / antecedent_support))
    139             if confidence >= self.min_conf:
    140                 # The concequent is the initial_itemset except for antecedent

ZeroDivisionError: float division by zero

**Comment by eriklindernoren** [comment]
This should be fixed in the latest commit.

**Comment by eriklindernoren** [comment]
- Apriori -
Minimum - support: 0.20, confidence: 0.8
Transactions:
	[1, 2, 3, 4]
	[1, 2, 4]
	[1, 2]
	[2, 3, 4]
	[2, 3]
	[3, 4]
	[2, 4]
Frequent Itemsets:
	[1, 2, 3, 4, [1, 2], [1, 4], [2, 3], [2, 4], [3, 4], [1, 2, 4], [2, 3, 4]]
Rules:
	1 -> 2 (support: 0.43, confidence: 1.0)
	4 -> 2 (support: 0.57, confidence: 0.8)
	[1, 4] -> 2 (support: 0.29, confidence: 1.0)
