### ISSUE TITLE
naive_bayes

### ISSUE THREAD

**Issue by rebornwwp** [eriklindernoren/ML-From-Scratch#15]
### in the navie bayes , X refer to Gaussian probability distribution, why? 
because you define X is continuous,？

thanks

**Comment by eriklindernoren** [comment]
Yes, this is an implementation of Gaussian Naive Bayes where it is assumed that the continuous random variables are distributed according to a Gaussian Distribution. 

You can read more about it here:
https://en.wikipedia.org/wiki/Naive_Bayes_classifier#Gaussian_naive_Bayes

**Comment by eriklindernoren** [comment]
Feel free to email me if you have further questions.
