### ISSUE TITLE
mlfromscratch/supervised_learning/__init__.py has references to undefined python files.

### ISSUE THREAD

**Issue by sentientmachine** [eriklindernoren/ML-From-Scratch#22]
Everything you need to know is in the title. ` mlfromscratch/supervised_learning/__init__.py` has references to undefined python files.

To reproduce, run: "python demo.py", you get:

    ImportError: No module named linear_regression

Because `supervisedLearning/__init__.py` has references to regression classes in files that don't exist.

I was able to correct them in my fork and rebuild and all is well, just have to rename the "whatever_regression" to regression and do the setup again.

Thinking it over, these may be intentional as an exercise for the user.  Good job.  :1st_place_medal:

**Comment by eriklindernoren** [comment]
Haha. Thanks! The regression models used to be separated in different files.
