### ISSUE TITLE
MatplotlibWrapper is an undefined name

### ISSUE THREAD

**Issue by cclauss** [eriklindernoren/ML-From-Scratch#23]
MatplotlibWrapper is an undefined name in gaussian_mixture_model.py and k_means.py.  Undefined names can raise [NameError](https://docs.python.org/3/library/exceptions.html#NameError) at runtime.

flake8 testing of https://github.com/eriklindernoren/ML-From-Scratch on Python 2.7.13

$ flake8 . --count --select=E901,E999,F821,F822,F823 --show-source --statistics
```
./mlfromscratch/unsupervised_learning/gaussian_mixture_model.py:137:9: F821 undefined name 'MatplotlibWrapper'
    p = MatplotlibWrapper()
        ^
```

The same issue is __also present in k_means.py__ but [the * import](https://github.com/eriklindernoren/ML-From-Scratch/blob/master/mlfromscratch/unsupervised_learning/k_means.py#L11) masks it from flake8.

**Comment by eriklindernoren** [comment]
Thanks. This is fixed in https://github.com/eriklindernoren/ML-From-Scratch/commit/d58485e573f99a86b6033f0cd793d01fb6b423a9
