### ISSUE TITLE
k-means: TypeError: make_blobs() got an unexpected keyword argument 'noise'

### ISSUE THREAD

**Issue by gyosh** [eriklindernoren/ML-From-Scratch#3]
# Reproduction

```python
python unsupervised_learning/k_means.py 
```

# Diagnosis

This line caused the error:

```python
X, y = datasets.make_blobs(noise=0.1)
```

Checked all scikit documentation for make_blobs:

  * http://scikit-learn.org/stable/modules/generated/sklearn.datasets.make_blobs.html
  * http://scikit-learn.org/0.17/modules/generated/sklearn.datasets.make_blobs.html
  * http://scikit-learn.org/0.16/modules/generated/sklearn.datasets.make_blobs.html
  * http://scikit-learn.org/0.15/modules/generated/sklearn.datasets.make_blobs.html

None of them has `noise` parameter.

Perhaps what's needed is `cluster_std`?

**Comment by eriklindernoren** [comment]
Oh, yes you're right. I used a different dataset earlier that had a noise parameter. It is fixed in the latest commit.
