### ISSUE TITLE
suggest renaming of acc_grad 

### ISSUE THREAD

**Issue by tomVeloso** [eriklindernoren/ML-From-Scratch#32]
https://github.com/eriklindernoren/ML-From-Scratch/blob/c5256ff2d9e507a055094d7ce8064138706ab483/mlfromscratch/deep_learning/neural_network.py#L100  since you use .acc .loss in the function loss .. can be better change the name of the variable acc_grad

**Comment by eriklindernoren** [comment]
Hi,

Thanks for your feedback. Renaming `acc_grad` is a good suggestion. I changed the variable name in `mlfromscratch/deep_learning/layers.py` to `accum_grad`.

See c5256ff.

Cheers,
Erik
