### ISSUE TITLE
Missing random feature selection in Random Forest construction.

### ISSUE THREAD

**Issue by cesar0205** [eriklindernoren/ML-From-Scratch#40]
As far I am concerned when constructing each tree in the random forest it is necessary to choose a random subset of features at "each" node of the tree, so a DecisionTree class can't be reused.
1) Sample a random subset of the training data. (bagging)
2) At each node of the tree sample a random subset of the original features and select the best.

What I observed in this implementation is that you are reusing the DecisionTree class and only randomly sampling the features once throughout all the tree.
1) Sample a random subset of the training data. (bagging)
2) Sample a random subset of the features of the sampled data.
3) Feed the data into a DecisionTree.

I would like to know whether this is a legit implementation and where could I find more information about this implementation option.

By the way, your work is awesome and is helping students like me understand deeply machine learning algorithms.

**Comment by leferrad** [comment]
I don't agree with the idea of fitting a RandomForest by selecting the best features from a random subset at each node of a given tree, or at least I didn't understand it. I've just reviewed the code and it seems to behave as correct as I know, and actually it doesn't reuse DecisionTrees as you said so I don't get the problem with the behavior:

1. [Here](https://github.com/eriklindernoren/ML-From-Scratch/blob/master/mlfromscratch/supervised_learning/random_forest.py#L43-L49) the decision trees are initialized separately by getting instances of the class `ClassificationTree` and storing them into a list (as in any OOP program, objects are not the same than classes). Therefore, the RF doesn't use the same tree for predictions.
2. [Here](https://github.com/eriklindernoren/ML-From-Scratch/blob/master/mlfromscratch/supervised_learning/random_forest.py#L64-L70) occurs the sample of feature for each tree, by getting indexes of the whole set of features and fitting the given tree with the selection of those features. Therefore, every tree is fitted with a random selection of features in a separate way. 

Let me know the algorithm that you wanted to explain (through a link or a paper citation) to compare the implementations, but so far I think this implementation is correct. In addition, I also congrats for the whole repository, it's great to have a prolix set of implementation of the most important algorithms handled in ML.
