### ISSUE TITLE
Genetic algorithm mutation rate

### ISSUE THREAD

**Issue by alojoecee** [eriklindernoren/ML-From-Scratch#49]
Issue with Genetic algorithm commit at Unsupervised learning. 

The approach taken towards the initiation of mutation is a bit unrealistic. Given the fact that the mutation rate provided by the user isn't treated as a rate in it's original sense but rather it's being compared directly with the Numpy's random value, which makes it useless even if a high mutation rate was set.

**Comment by eriklindernoren** [comment]
Given that the mutation rate parameter is compared against a value sampled randomly between 0 and 1 mutation will be applied in proportion to the mutation rate value provided. E.g. for mutation rate set to 0.6, mutation will be applied ~60% of the times given that the random value is uniformly sampled between 0 and 1.

**Comment by alojoecee** [comment]
Run this experimental code. 

import numpy 
mutation_rate = 0.6
times = 0
for i in range(10):
	if numpy.random.random() < mutation_rate:
		times += 0.1
print(times)

The random value is uniformly sampled but it isn't applied 60% of the time. It is also random.

**Comment by alojoecee** [comment]
Run this experimental code.

``import numpy 
mutation_rate = 0.6
times = 0
for i in range(10):
	if numpy.random.random() < mutation_rate:
		times += 0.1
print(times)

The random value is uniformly sampled but it isn't applied 60% of the time. It is also random.

**Comment by eriklindernoren** [comment]
It's applied 100% of the time but is true roughly 60% of the time. See below.

```
Eriks-MacBook-Pro:~ erik$ python3
Python 3.7.0 (default, Jun 29 2018, 20:13:13) 
[Clang 9.1.0 (clang-902.0.39.2)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy as np
>>> val = 0
>>> for _ in range(100000):
...     if np.random.random() < 0.6:
...             val += 1
... 
>>> print (val)
59966
```

**Comment by alojoecee** [comment]
Run it multiple times and compare the results. Numpy's random value generation is independent of boolean comparisons.

**Comment by eriklindernoren** [comment]
Mutation rate is commonly implemented as a probability of mutation with respect to the mutation rate parameter. Because of this it's implemented as a comparison between a random value and the parameter.

**Comment by alojoecee** [comment]
You don't understand what I was trying to communicate, anyways, you did a good job.

**Comment by eriklindernoren** [comment]
This is handled similarly to what I've seen in several other reference implementations of GE. Check https://blog.sicara.com/getting-started-genetic-algorithms-python-tutorial-81ffa1dd72f9 in the section where mutation is implemented for instance. The argument that setting a higher mutation rate would not have an impact is clearly false as the statement `np.random.random() < mutation_rate` would be true more often and mutation would thereby be applied.
