### ISSUE TITLE
Need requirements file to install required modules.

### ISSUE THREAD

**Issue by tanaydin** [eriklindernoren/ML-From-Scratch#5]
This code has some requirements to run. Generally a requirements.txt file keeps track of this libraries.

[requirements.txt](https://github.com/eriklindernoren/ML-From-Scratch/files/802065/requirements.txt)

you can use it like

`pip install -r requirements.txt`

**Comment by eriklindernoren** [comment]
Added a requirements file which hopefully covers any dependency.
